language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6 --prefer-source --no-interaction --dev

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != *hhvm* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
