language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - if [[ "$TRAVIS_PHP_VERSION" == *5.6* ]]; then travis_retry composer require "satooshi/php-coveralls:~0.6.1" "symfony/yaml=~2.0" --prefer-source --no-interaction --dev; else travis_retry composer install --prefer-source --no-interaction; fi

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == *5.6* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
