language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - DEFAULT=1

before_script:
  - travis_retry composer self-update
  - if [[ $DEFAULT = '1' ]]; then travis_retry composer install --prefer-source --no-interaction; fi
  - if [[ $COVERALLS == '1' ]]; then travis_retry composer require "satooshi/php-coveralls=~0.6" "symfony/yaml=~2.0" --prefer-source --no-interaction --dev; fi

script:
  - if [[ $COVERALLS == '1' ]]; then phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $DEFAULT = '1' ]]; then phpunit -c phpunit.xml; fi

after_script:
  - if [[ $COVERALLS == '1' ]]; then php vendor/bin/coveralls -v; fi

matrix:
  include:
    - php: 5.4
      env: COVERALLS=1 DEFAULT=0
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
